INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
    VALUES (1, 'Syrup - Monin, Amaretta', 4.99);
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
    VALUES (2, 'Banana Turning', 2.99);
INSERT INTO PRODUCTS (PRODUCT_ID, NAME, PRICE)
    VALUES (3, 'Flower - Carnations', 12.99);
